<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'AnimeStudio' Or '$(MSBuildProjectName)' == 'AnimeStudio.CLI' Or '$(MSBuildProjectName)' == 'AnimeStudio.GUI'">
    <Version>1.2.2</Version>
    <AssemblyVersion>1.2.2</AssemblyVersion>
    <FileVersion>1.2.2</FileVersion>
  </PropertyGroup>
</Project>
