<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0;net10.0</TargetFrameworks>
		<Copyright>Copyright © Escartem 2024-2026; Copyright © yarik0chka 2024-2025; Copyright © Hashblen 2024-2025; Copyright © Razmoth 2022-2024; Copyright © Perfare 2018-2022</Copyright>
		<DebugType>embedded</DebugType>
		<SelfContained>false</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="K4os.Hash.xxHash" Version="1.0.8" />
		<PackageReference Include="Kyaru.Texture2DDecoder" Version="0.17.1" />
		<PackageReference Include="Kyaru.Texture2DDecoder.Windows" Version="0.2.0" />
		<PackageReference Include="MessagePack" Version="3.1.10" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
		<PackageReference Include="SkiaSharp" Version="3.119.4" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="CNKeys.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<ContentWithTargetPath Include="..\AnimeStudio.Libraries\AnimeStudio.Ooz.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>AnimeStudio.Ooz.dll</TargetPath>
		</ContentWithTargetPath>
		<ContentWithTargetPath Include="..\AnimeStudio.Libraries\AnimeStudio.FBXNative.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>AnimeStudio.FBXNative.dll</TargetPath>
		</ContentWithTargetPath>
	</ItemGroup>

</Project>
